# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: englishpage_development
  user: joseph

test:
  adapter: postgresql
  database: englishpage_test
  user: joseph

production:
  adapter: postgresql
  database: englishpage_production
  user: joseph
